#!/usr/bin/python3
# -*-Python-*-

import sys
import getopt
import hiveconf

VERSION="0.0"
DEFAULT_TYPE="string"
DEFAULT_ROOT_HIVE="/etc/root.hconf"

#
# Utility classes and functions
#

class _IndentPrinter:
    def __init__(self):
        self.indent = 0
        self.line_indented = 0

    def write(self, data):
        if self.indent and not self.line_indented:
            sys.stdout.write(" " * self.indent)
            self.line_indented = 1
        sys.stdout.write(data)
        if data.find("\n") != -1:
            self.line_indented = 0

    def change(self, val):
        self.indent += val

def _unicode_to_print(*args, folder=None, **kwargs):
    try:
        print(*args, file=kwargs["file"])
    except UnicodeEncodeError:
        if folder:
            if len(folder.sources) > 0:
                raise hiveconf.UnicodeError("Characters in [%s] in %s cannot be printed." \
                                    % (folder.sectionname, folder.sources[0]))
            else:
                raise hiveconf.UnicodeError("Characters in [%s] cannot be printed." \
                                    % (folder.sectionname))

#
# End of utility classes and functions
#


def get_type(s):
    """Parse parameter string. Returns (type, parameter)"""
    words = s.split(":", 1)
    if not words[1:]:
        # No colon in string
        return (DEFAULT_TYPE, s)
    
    (beforecolon, aftercolon) = words
    if beforecolon in ("string", "bool", "integer", "float", "binary",
                       "string_list", "bool_list", "integer_list",
                       "float_list", "binary_list"):
        return (beforecolon, aftercolon)
    else:
        return (DEFAULT_TYPE, s)


def get_value(s):
    """Parse parameter string. Returns (parameterpath, value)"""
    words = s.split("=", 1)
    if not words[1:]:
        # No equal sign in string
        return (s, None)
    else:
        return tuple(words)


def handle_param(hive, param):
    """Print parameter. Returns zero on success"""
    (paramtype, param) = get_type(param)
    (parampath, value) = get_value(param)

    if not value:
        # Display value
        method = getattr(hive, "get_%s" % paramtype)
        try:
            value = method(parampath)
        except hiveconf.NotAParameterError:
            print("%s: Not a parameter" % parampath, file=sys.stderr)
            return 1
            
        if value == None:
            print("%s: No such parameter" % parampath, file=sys.stderr)
            return 1
        else:
            print(value)
    else:
        # Set value
        method = getattr(hive, "set_%s" % paramtype)
        if not method(parampath, value):
            print("Failed to set parameter", parampath, file=sys.stderr)
            return 1
    return 0


def eval_print(hive, varname, param, export):
    (paramtype, parampath) = get_type(param)
    method = getattr(hive, "get_%s" % paramtype)
    value = method(parampath)
    if export:
        print("export", end=' ')
    if value:
        value = str(value)
        # ' is the only character that needs special handling
        value = value.replace("'", "'\\''")
        print("%s='%s'" % (varname, value))
    else:
        print("%s=''" % varname)
    if value == None:
        return 1
    else:
        return 0


def imp_walk(hive, ih, folderpath):
    # Handle parameters and values
    for paramname in ih.get_parameters(folderpath):
        parampath = folderpath + "/" + paramname
        value = ih.get_string(parampath)
        #print "setting", parampath, "to", value
        hive.set_string(parampath, value)
        if parampath in purge_params:
            purge_params.remove(parampath)

    for subname in ih.get_folders(folderpath):
        if subname == "/":
            continue
        if folderpath != "/":
            subname = "/" + subname
        subfolder = folderpath + subname
        imp_walk(hive, ih, subfolder)

# A list of parameters to delete
purge_params = []

def purge_walk(hive, ph, folderpath):
    # Handle parameters and values
    for paramname in ph.get_parameters(folderpath):
        parampath = folderpath + "/" + paramname
        if hive.lookup(parampath) != None:
            # Add to delete-list
            purge_params.append(parampath)

    for subname in ph.get_folders(folderpath):
        if subname == "/":
            continue
        if folderpath != "/":
            subname = "/" + subname
        subfolder = folderpath + subname
        purge_walk(hive, ph, subfolder)


def print_walk(folder, recursive=1, indent=None):
    if not indent:
        indent = _IndentPrinter()

    # Print Parameters and values
    for (paramname, param) in folder._parameters.items():
        _unicode_to_print(paramname, "=", param.get_string(), file=indent,
                          folder=folder)

    # Print Foldernames and their contents
    for (foldername, folder) in folder._folders.items():
        if foldername == "/":
            continue

        _unicode_to_print(foldername + "/ ", file=indent, folder=folder)

        indent.change(4)
        if recursive:
            print_walk(folder, recursive, indent)
        indent.change(-4)


def usage():
    print("""
hivetool [options] [type:]parameter[=value] ...

  -a,--all-entries        Print all parameters and values in a folder
  -i,--import <file>      Import all parameters in specified file
  -p,--purge <file>       Remove parameters in specified file which exists elsewhere
  -R,--recursive	  When using -a, ascend folders recursively
  -r,--root <file>	  Specify root hive file. Default is /etc/root.hconf
  -e,--eval VAR=parameter Print parameter value in format suitable for
                          assignment to shell variable, via evaluation
  -E folder               As -e, but print all parameters in specified folder
  -v,--version		  Print version
  -x,--export             When using -e,-E, export variables
  -?,--help		  Show this help message

  type is one of: string, bool, integer, float, binary, string_list,
  bool_list, integer_list, float_list, binary_list. Default is string

  Example:

  hivetool -Ra /

  hivetool -r /etc/samba/smb.conf /global/workgroup=MYWORKGROUP

  hivetool -p /etc/samba/smb.conf -i /etc/samba/smb.conf.rpmsave
""", file=sys.stderr)



def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:i:p:Rr:ve:E:x?",
                                   ["all-entries=", "import=", "purge=", "recursive", "root=", "version", "help",
                                    "eval=", "export"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    roothive = DEFAULT_ROOT_HIVE
    walk_folders = []
    imp_files = []
    purge_files = []
    recursive = 0
    e_params =[]
    E_params = []
    eval_export = 0 
    for o, a in opts:
        if o in ("-a", "--all-entries"):
            walk_folders.append(a)
        if o in ("-i", "--import"):
            imp_files.append(a)
        if o in ("-p", "--purge"):
            purge_files.append(a)
        if o in ("-R", "--recursive"):
            recursive = 1
        if o in ("-r", "--root"):
            roothive = a
        if o in ("-v", "--version"):
            print("hivetool version", VERSION, file=sys.stderr)
            sys.exit(0)
        if o in ("-e", "--eval"):
            words = a.split("=", 1)
            if not words[1:]:
                usage()
                sys.exit(2)
            e_params.append(words)
        if o in ("-E",):
            E_params.append(a)
        if o in ("-x", "--export"):
            eval_export = 1
        if o in ("-?", "--help"):
            usage()
            sys.exit(0)

    errors = 0

    # Try to open root hive
    hive = hiveconf.open_hive(roothive)

    # Retrieve parameters to purge from specified files
    for purge_file in purge_files:
        ph = hiveconf.open_hive(purge_file)
        reduced_hive = hiveconf.open_hive(roothive, blacklist=[purge_file])
        purge_walk(reduced_hive, ph, "/")

    # Import specified files
    for imp_file in imp_files:
        ih = hiveconf.open_hive(imp_file)
        imp_walk(hive, ih, "/")

    # Actually purge. Note that if you specify all files where the
    # parameter is defined as purge files, then all instances of the
    # parameter will be deleted.
    for purge_file in purge_files:
        ph = hiveconf.open_hive(purge_file)
        for pp in purge_params:
            ph.delete(pp)

    # Handle -e parameters
    for (varname, param) in e_params:
        errors += eval_print(hive, varname, param, eval_export)

    # Handle -E
    for foldername in E_params:
        folder = hive.lookup(foldername)
        params = hive.get_parameters(foldername)
        for param in params:
            errors += eval_print(folder, param, param, eval_export)

    # Get/set listed parameters
    for param in args:
        errors += handle_param(hive, param)

    # Walk
    for foldername in walk_folders:
        folder = hive.lookup(foldername)
        if not folder:
            print("%s: Folder not found" % foldername, file=sys.stderr)
            continue

        if not isinstance(folder, hiveconf.Folder):
            print("%s: not a folder" % foldername, file=sys.stderr)
            continue

        print_walk(folder, recursive)

    sys.exit(errors)

if __name__ == "__main__":
    main()

